apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  labels:
    app: filebeat
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log           # standard k8s container logs path (source - filebeat reads it)
      processors:
        - add_kubernetes_metadata:            # enriches logs with metadata (namespaces, pods etc real names)
            host: ${NODE_NAME}                # filebeat needs to know its current node to ask accurate metadata (see line 52 - env var)
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"

    output.elasticsearch:                     
      hosts: ['elasticsearch:9200']           # processed logs are sent to elasticsearch

---
apiVersion: apps/v1
kind: DaemonSet # daemonset ensures that only 1 replica runs on each cluster node
metadata:
  name: filebeat
  labels:
    app: filebeat
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat

    spec:
      serviceAccountName: filebeat (rbac.yaml)

      securityContext: # forces container to run as root, to read /var/log (owned by root)
        runAsUser: 0

      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:7.17.10
        args: [                       # disable strict permission checks - for lab purposes, not for production
          "-c", "/etc/filebeat.yml",
          "-e",
          "--strict.perms=false" 
        ]

        env: # captures the node name (spec.nodeName) into NODE_NAME variable (see line 15)
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName

        volumeMounts:
        # mounts the configmap created above as a file
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml # mounts only filebeat.yaml without overwriting the rest of /etc
        # path of registry (see line 82)
        - name: data
          mountPath: /usr/share/filebeat/data
        # access to host: mounts raw docker json logs
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        # access to host: mounts symbolic links created by k8s 
        - name: varlog
          mountPath: /var/log
          readOnly: true

      volumes:
      - name: config
        configMap:
          defaultMode: 0640 # chmod 640
          name: filebeat-config
      # persistence: creates a directory on the host so filebeat can store its "registry" (pointer from where it stopped reading)
      - name: data
        hostPath: # hostpath: a "mirror" of the server (same to the following volumes)
          path: /var/lib/filebeat-data
          type: DirectoryOrCreate # creates the directory if it doesn't exist
      # where docker stores raw json logs
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      # where k8s maintains organized logs symlinks
      - name: varlog
        hostPath:
          path: /var/log